namespace: nokia
name: sros
version: 1.8.0
readme: README.md
authors:
- Sven Wisotzky <sven.wisotzky@nokia.com>
description: Ansible collection to support networking devices running Nokia SR OS
license: BSD-3-Clause
requires_ansible: ">=2.13"
tags:
- backup
- nokia
- sros
- timos
- netconf
- cli
- cliconf
- terminal

repository: https://github.com/nokia/sros-ansible
documentation: https://github.com/nokia/sros-ansible
homepage: https://github.com/nokia/sros-ansible
issues: http://github.com/nokia/sros-ansible/issues
