---
- hosts: nokia
  vars:
    ansible_network_os: nokia.sros.md
    ansible_user: admin
    ansible_password: admin
    ansible_command_timeout: 30
  connection: network_cli
  gather_facts: No

  collections:
  - nokia.sros

  tasks:
  - name: add services
    cli_config:
      config: "{{ lookup('template', 'addVplsBulk.cli.j2') }}"

  - name: admin save
    cli_command:
      command: admin save
    vars:
      ansible_command_timeout: 60

  - name: delete services
    cli_config:
      config: "{{ lookup('template', 'delVplsBulk.cli.j2') }}"

  - name: admin save
    cli_command:
      command: admin save
    vars:
      ansible_command_timeout: 60
...
