name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: ./tools/run.sh deps
      - name: Run sanity checks
        run: ./tools/run.sh sanity
      - name: Build collection artifact
        run: ./tools/run.sh build
      - name: Publish to Ansible Galaxy
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
        run: |
          if [ -z "$ANSIBLE_GALAXY_API_KEY" ]; then
            echo "ANSIBLE_GALAXY_API_KEY is not set. Skipping publish step." >&2
            exit 1
          fi
          ansible-galaxy collection publish dist/nokia-sros-*.tar.gz --api-key "$ANSIBLE_GALAXY_API_KEY"
