name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssh-dev

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build and install this collection
        run: |
          ansible-galaxy collection build .

      - name: Extract collection metadata
        id: meta
        run: |
          ORG=$(yq '.namespace' galaxy.yml)
          COLLECTION=$(yq '.name' galaxy.yml)
          VERSION=$(yq '.version' galaxy.yml)

          FILENAME="${ORG}-${COLLECTION}-${VERSION}.tar.gz"
          if [ ! -f "$FILENAME" ]; then
            echo "Collection artifact $FILENAME not found" >&2
            exit 1
          fi

          echo "FILENAME=$FILENAME" >> "$GITHUB_ENV"

      - name: Upload workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-collection
          path: ${{ env.FILENAME }}

      - name: Attach collection to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Ansible Galaxy
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
        run: |
          if [ -z "$ANSIBLE_GALAXY_API_KEY" ]; then
            echo "ANSIBLE_GALAXY_API_KEY is not set. Skipping publish step." >&2
            exit 1
          fi
          ansible-galaxy collection publish ${{ env.FILENAME }} --api-key "$ANSIBLE_GALAXY_API_KEY"
